In [1]:
import json
import pandas as pd

with open("zeek_semantic_mappingDB.json", "r", encoding="utf-8") as f:
    zeek_semantic = json.load(f)
with open("zeek_correlation_mappingDB.json", "r", encoding="utf-8") as f:
    zeek_correlation = json.load(f)
with open("wazuh_mappingDB.json", "r", encoding="utf-8") as f:
    wazuh = json.load(f)

zeek_semantic_mapping = zeek_semantic["mappings"]
zeek_correlation_mapping = zeek_correlation["mappings"]
wazuh_mapping  = wazuh["mappings"]

mappings = (
    zeek_semantic_mapping
    + zeek_correlation_mapping
    + wazuh_mapping
)


techniques_by_id = {}

for m in mappings:
    technique = m["attack_technique"]
    technique_id = technique["technique_id"]

    techniques_by_id[technique_id] = technique
techniques_by_id

{'T1590.001': {'technique_id': 'T1590.001',
  'technique_name': 'Gather Victim Network Information: Domain Properties',
  'tactic': 'Reconnaissance'},
 'T1016': {'technique_id': 'T1016',
  'technique_name': 'System Network Configuration Discovery',
  'tactic': 'Discovery'},
 'T1190': {'technique_id': 'T1190',
  'technique_name': 'Exploit Public-Facing Application',
  'tactic': 'Initial Access'},
 'T1133': {'technique_id': 'T1133',
  'technique_name': 'External Remote Services',
  'tactic': 'Initial Access'},
 'T1078': {'technique_id': 'T1078',
  'technique_name': 'Valid Accounts',
  'tactic': 'Initial Access'},
 'T1505.003': {'technique_id': 'T1505.003',
  'technique_name': 'Server Software Component: Web Shell',
  'tactic': 'Persistence'},
 'T1105': {'technique_id': 'T1105',
  'technique_name': 'Ingress Tool Transfer',
  'tactic': 'Command and Control'},
 'T1203': {'technique_id': 'T1203',
  'technique_name': 'Exploitation for Client Execution',
  'tactic': 'Execution'},
 'T1204': {'technique_id': 'T1204',
  'technique_name': 'User Execution',
  'tactic': 'Execution'},
 'T1021.001': {'technique_id': 'T1021.001',
  'technique_name': 'Remote Services: Remote Desktop Protocol',
  'tactic': 'Lateral Movement'},
 'T1021.002': {'technique_id': 'T1021.002',
  'technique_name': 'Remote Services: SMB/Windows Admin Shares',
  'tactic': 'Lateral Movement'},
 'T1021.004': {'technique_id': 'T1021.004',
  'technique_name': 'Remote Services: SSH',
  'tactic': 'Lateral Movement'},
 'T1046': {'technique_id': 'T1046',
  'technique_name': 'Network Service Scanning',
  'tactic': 'Reconnaissance'},
 'T1595.001': {'technique_id': 'T1595.001',
  'technique_name': 'Active Scanning: Scanning IP Blocks',
  'tactic': 'Reconnaissance'},
 'T1595.002': {'technique_id': 'T1595.002',
  'technique_name': 'Active Scanning: Vulnerability Scanning',
  'tactic': 'Reconnaissance'},
 'T1590.002': {'technique_id': 'T1590.002',
  'technique_name': 'Gather Victim Network Information: DNS',
  'tactic': 'Reconnaissance'},
 'T1592': {'technique_id': 'T1592',
  'technique_name': 'Gather Victim Host Information',
  'tactic': 'Reconnaissance'},
 'T1083': {'technique_id': 'T1083',
  'technique_name': 'File and Directory Discovery',
  'tactic': 'Discovery'},
 'T1018': {'technique_id': 'T1018',
  'technique_name': 'Remote System Discovery',
  'tactic': 'Discovery'},
 'T1049': {'technique_id': 'T1049',
  'technique_name': 'System Network Connections Discovery',
  'tactic': 'Discovery'},
 'T1110': {'technique_id': 'T1110',
  'technique_name': 'Brute Force',
  'tactic': 'Credential Access'},
 'T1110.001': {'technique_id': 'T1110.001',
  'technique_name': 'Brute Force: Password Guessing',
  'tactic': 'Credential Access'},
 'T1110.003': {'technique_id': 'T1110.003',
  'technique_name': 'Brute Force: Password Spraying',
  'tactic': 'Credential Access'},
 'T1210': {'technique_id': 'T1210',
  'technique_name': 'Exploitation of Remote Services',
  'tactic': 'Lateral Movement'},
 'T1071.001': {'technique_id': 'T1071.001',
  'technique_name': 'Application Layer Protocol: Web Protocols',
  'tactic': 'Command and Control'},
 'T1071.004': {'technique_id': 'T1071.004',
  'technique_name': 'Application Layer Protocol: DNS',
  'tactic': 'Command and Control'},
 'T1572': {'technique_id': 'T1572',
  'technique_name': 'Protocol Tunneling',
  'tactic': 'Command and Control'},
 'T1095': {'technique_id': 'T1095',
  'technique_name': 'Non-Application Layer Protocol',
  'tactic': 'Command and Control'},
 'T1041': {'technique_id': 'T1041',
  'technique_name': 'Exfiltration Over C2 Channel',
  'tactic': 'Exfiltration'},
 'T1048.003': {'technique_id': 'T1048.003',
  'technique_name': 'Exfiltration Over Unencrypted/Obfuscated Non-C2 Protocol',
  'tactic': 'Exfiltration'},
 'T1567': {'technique_id': 'T1567',
  'technique_name': 'Exfiltration Over Web Service',
  'tactic': 'Exfiltration'},
 'T1048': {'technique_id': 'T1048',
  'technique_name': 'Exfiltration Over Alternative Protocol',
  'tactic': 'Exfiltration'},
 'T1039': {'technique_id': 'T1039',
  'technique_name': 'Data from Network Shared Drive',
  'tactic': 'Collection'},
 'T1213': {'technique_id': 'T1213',
  'technique_name': 'Data from Information Repositories',
  'tactic': 'Collection'},
 'T1071.002': {'technique_id': 'T1071.002',
  'technique_name': 'Application Layer Protocol: File Transfer Protocols',
  'tactic': 'Command and Control'},
 'T1496': {'technique_id': 'T1496',
  'technique_name': 'Resource Hijacking',
  'tactic': 'Impact'},
 'T1497': {'technique_id': 'T1497',
  'technique_name': 'Virtualization/Sandbox Evasion',
  'tactic': 'Defense Evasion'},
 'T1568.002': {'technique_id': 'T1568.002',
  'technique_name': 'Dynamic Resolution: Domain Generation Algorithms',
  'tactic': 'Command and Control'},
 'T1189': {'technique_id': 'T1189',
  'technique_name': 'Drive-by Compromise',
  'tactic': 'Initial Access'},
 'T1059.001': {'technique_id': 'T1059.001',
  'technique_name': 'Command and Scripting Interpreter: PowerShell',
  'tactic': 'Execution'},
 'T1059': {'technique_id': 'T1059',
  'technique_name': 'Command and Scripting Interpreter',
  'tactic': 'Execution'},
 'T1003.001': {'technique_id': 'T1003.001',
  'technique_name': 'OS Credential Dumping: LSASS Memory',
  'tactic': 'Credential Access'},
 'T1003.008': {'technique_id': 'T1003.008',
  'technique_name': 'OS Credential Dumping: /etc/passwd and /etc/shadow',
  'tactic': 'Credential Access'},
 'T1027': {'technique_id': 'T1027',
  'technique_name': 'Obfuscated Files or Information',
  'tactic': 'Defense Evasion'},
 'T1204.002': {'technique_id': 'T1204.002',
  'technique_name': 'User Execution: Malicious File',
  'tactic': 'Execution'},
 'T1547.001': {'technique_id': 'T1547.001',
  'technique_name': 'Boot or Logon Autostart Execution: Registry Run Keys',
  'tactic': 'Persistence'},
 'T1053.005': {'technique_id': 'T1053.005',
  'technique_name': 'Scheduled Task/Job: Cron',
  'tactic': 'Persistence'},
 'T1543.003': {'technique_id': 'T1543.003',
  'technique_name': 'Create or Modify System Process: Windows Service',
  'tactic': 'Persistence'},
 'T1087.002': {'technique_id': 'T1087.002',
  'technique_name': 'Account Discovery: Domain Account',
  'tactic': 'Discovery'},
 'T1069.002': {'technique_id': 'T1069.002',
  'technique_name': 'Permission Groups Discovery: Domain Groups',
  'tactic': 'Discovery'},
 'T1059.004': {'technique_id': 'T1059.004',
  'technique_name': 'Unix Shell',
  'tactic': 'Execution'},
 'T1548.003': {'technique_id': 'T1548.003',
  'technique_name': 'Sudo and Sudo Caching',
  'tactic': 'Privilege Escalation'},
 'T1033': {'technique_id': 'T1033',
  'technique_name': 'System Owner/User Discovery',
  'tactic': 'Discovery'}}

In [5]:
import requests
import pandas as pd

url = "https://raw.githubusercontent.com/mitre-attack/attack-stix-data/refs/heads/master/enterprise-attack/enterprise-attack.json"

response = requests.get(url)
response.raise_for_status()

data = response.json()

df = pd.DataFrame(data["objects"])

techniques_df = df[df["type"] == "attack-pattern"].copy()

groups_df = df[df["type"] == "intrusion-set"].copy()

relationships_df = df[df["type"] == "relationship"].copy()

tactics_df = df[df["type"] == "x-mitre-tactic"].copy()

campaigns_df = df[df["type"] == "campaign"].copy()

print(techniques_df.shape)
print(groups_df.shape)
print(relationships_df.shape)
print(tactics_df.shape)
print(campaigns_df.shape)

supported_techniques = {'T1590.001': {'technique_id': 'T1590.001',
  'technique_name': 'Gather Victim Network Information: Domain Properties',
  'tactic': 'Reconnaissance'},
 'T1016': {'technique_id': 'T1016',
  'technique_name': 'System Network Configuration Discovery',
  'tactic': 'Discovery'},
 'T1190': {'technique_id': 'T1190',
  'technique_name': 'Exploit Public-Facing Application',
  'tactic': 'Initial Access'},
 'T1133': {'technique_id': 'T1133',
  'technique_name': 'External Remote Services',
  'tactic': 'Initial Access'},
 'T1078': {'technique_id': 'T1078',
  'technique_name': 'Valid Accounts',
  'tactic': 'Initial Access'},
 'T1505.003': {'technique_id': 'T1505.003',
  'technique_name': 'Server Software Component: Web Shell',
  'tactic': 'Persistence'},
 'T1105': {'technique_id': 'T1105',
  'technique_name': 'Ingress Tool Transfer',
  'tactic': 'Command and Control'},
 'T1203': {'technique_id': 'T1203',
  'technique_name': 'Exploitation for Client Execution',
  'tactic': 'Execution'},
 'T1204': {'technique_id': 'T1204',
  'technique_name': 'User Execution',
  'tactic': 'Execution'},
 'T1021.001': {'technique_id': 'T1021.001',
  'technique_name': 'Remote Services: Remote Desktop Protocol',
  'tactic': 'Lateral Movement'},
 'T1021.002': {'technique_id': 'T1021.002',
  'technique_name': 'Remote Services: SMB/Windows Admin Shares',
  'tactic': 'Lateral Movement'},
 'T1021.004': {'technique_id': 'T1021.004',
  'technique_name': 'Remote Services: SSH',
  'tactic': 'Lateral Movement'},
 'T1046': {'technique_id': 'T1046',
  'technique_name': 'Network Service Scanning',
  'tactic': 'Reconnaissance'},
 'T1595.001': {'technique_id': 'T1595.001',
  'technique_name': 'Active Scanning: Scanning IP Blocks',
  'tactic': 'Reconnaissance'},
 'T1595.002': {'technique_id': 'T1595.002',
  'technique_name': 'Active Scanning: Vulnerability Scanning',
  'tactic': 'Reconnaissance'},
 'T1590.002': {'technique_id': 'T1590.002',
  'technique_name': 'Gather Victim Network Information: DNS',
  'tactic': 'Reconnaissance'},
 'T1592': {'technique_id': 'T1592',
  'technique_name': 'Gather Victim Host Information',
  'tactic': 'Reconnaissance'},
 'T1083': {'technique_id': 'T1083',
  'technique_name': 'File and Directory Discovery',
  'tactic': 'Discovery'},
 'T1018': {'technique_id': 'T1018',
  'technique_name': 'Remote System Discovery',
  'tactic': 'Discovery'},
 'T1049': {'technique_id': 'T1049',
  'technique_name': 'System Network Connections Discovery',
  'tactic': 'Discovery'},
 'T1110': {'technique_id': 'T1110',
  'technique_name': 'Brute Force',
  'tactic': 'Credential Access'},
 'T1110.001': {'technique_id': 'T1110.001',
  'technique_name': 'Brute Force: Password Guessing',
  'tactic': 'Credential Access'},
 'T1110.003': {'technique_id': 'T1110.003',
  'technique_name': 'Brute Force: Password Spraying',
  'tactic': 'Credential Access'},
 'T1210': {'technique_id': 'T1210',
  'technique_name': 'Exploitation of Remote Services',
  'tactic': 'Lateral Movement'},
 'T1071.001': {'technique_id': 'T1071.001',
  'technique_name': 'Application Layer Protocol: Web Protocols',
  'tactic': 'Command and Control'},
 'T1071.004': {'technique_id': 'T1071.004',
  'technique_name': 'Application Layer Protocol: DNS',
  'tactic': 'Command and Control'},
 'T1572': {'technique_id': 'T1572',
  'technique_name': 'Protocol Tunneling',
  'tactic': 'Command and Control'},
 'T1095': {'technique_id': 'T1095',
  'technique_name': 'Non-Application Layer Protocol',
  'tactic': 'Command and Control'},
 'T1041': {'technique_id': 'T1041',
  'technique_name': 'Exfiltration Over C2 Channel',
  'tactic': 'Exfiltration'},
 'T1048.003': {'technique_id': 'T1048.003',
  'technique_name': 'Exfiltration Over Unencrypted/Obfuscated Non-C2 Protocol',
  'tactic': 'Exfiltration'},
 'T1567': {'technique_id': 'T1567',
  'technique_name': 'Exfiltration Over Web Service',
  'tactic': 'Exfiltration'},
 'T1048': {'technique_id': 'T1048',
  'technique_name': 'Exfiltration Over Alternative Protocol',
  'tactic': 'Exfiltration'},
 'T1039': {'technique_id': 'T1039',
  'technique_name': 'Data from Network Shared Drive',
  'tactic': 'Collection'},
 'T1213': {'technique_id': 'T1213',
  'technique_name': 'Data from Information Repositories',
  'tactic': 'Collection'},
 'T1071.002': {'technique_id': 'T1071.002',
  'technique_name': 'Application Layer Protocol: File Transfer Protocols',
  'tactic': 'Command and Control'},
 'T1496': {'technique_id': 'T1496',
  'technique_name': 'Resource Hijacking',
  'tactic': 'Impact'},
 'T1497': {'technique_id': 'T1497',
  'technique_name': 'Virtualization/Sandbox Evasion',
  'tactic': 'Defense Evasion'},
 'T1568.002': {'technique_id': 'T1568.002',
  'technique_name': 'Dynamic Resolution: Domain Generation Algorithms',
  'tactic': 'Command and Control'},
 'T1189': {'technique_id': 'T1189',
  'technique_name': 'Drive-by Compromise',
  'tactic': 'Initial Access'},
 'T1059.001': {'technique_id': 'T1059.001',
  'technique_name': 'Command and Scripting Interpreter: PowerShell',
  'tactic': 'Execution'},
 'T1059': {'technique_id': 'T1059',
  'technique_name': 'Command and Scripting Interpreter',
  'tactic': 'Execution'},
 'T1003.001': {'technique_id': 'T1003.001',
  'technique_name': 'OS Credential Dumping: LSASS Memory',
  'tactic': 'Credential Access'},
 'T1003.008': {'technique_id': 'T1003.008',
  'technique_name': 'OS Credential Dumping: /etc/passwd and /etc/shadow',
  'tactic': 'Credential Access'},
 'T1027': {'technique_id': 'T1027',
  'technique_name': 'Obfuscated Files or Information',
  'tactic': 'Defense Evasion'},
 'T1204.002': {'technique_id': 'T1204.002',
  'technique_name': 'User Execution: Malicious File',
  'tactic': 'Execution'},
 'T1547.001': {'technique_id': 'T1547.001',
  'technique_name': 'Boot or Logon Autostart Execution: Registry Run Keys',
  'tactic': 'Persistence'},
 'T1053.005': {'technique_id': 'T1053.005',
  'technique_name': 'Scheduled Task/Job: Cron',
  'tactic': 'Persistence'},
 'T1543.003': {'technique_id': 'T1543.003',
  'technique_name': 'Create or Modify System Process: Windows Service',
  'tactic': 'Persistence'},
 'T1087.002': {'technique_id': 'T1087.002',
  'technique_name': 'Account Discovery: Domain Account',
  'tactic': 'Discovery'},
 'T1069.002': {'technique_id': 'T1069.002',
  'technique_name': 'Permission Groups Discovery: Domain Groups',
  'tactic': 'Discovery'},
 'T1059.004': {'technique_id': 'T1059.004',
  'technique_name': 'Unix Shell',
  'tactic': 'Execution'},
 'T1548.003': {'technique_id': 'T1548.003',
  'technique_name': 'Sudo and Sudo Caching',
  'tactic': 'Privilege Escalation'},
 'T1033': {'technique_id': 'T1033',
  'technique_name': 'System Owner/User Discovery',
  'tactic': 'Discovery'}}
needed_technique_ids = set(supported_techniques.keys())

print(len(needed_technique_ids))

(858, 43)
(191, 43)
(21262, 43)
(15, 43)
(56, 43)
53

In [6]:
def get_attack_id(external_references):
    if not isinstance(external_references, list):
        return None

    for ref in external_references:
        if ref.get("source_name") == "mitre-attack":
            return ref.get("external_id")

    return None

techniques_df["technique_id"] = (
    techniques_df["external_references"]
    .apply(get_attack_id)
)
techniques_df.head()

,type,id,x_mitre_attack_spec_version,name,x_mitre_version,description,created_by_ref,created,modified,x_mitre_contents,...,x_mitre_log_sources,x_mitre_collection_layers,x_mitre_analytic_refs,relationship_type,source_ref,target_ref,identity_class,definition,definition_type,technique_id
1344,attack-pattern,attack-pattern--0042a9f5-f053-4769-b3ef-9ad018...,3.3.0,Extra Window Memory Injection,2.0,Adversaries may inject malicious code into pro...,identity--c78cb6e5-0c4b-4611-8297-d1b8b55e40b5,2020-01-14T17:18:32.126Z,2026-05-12T15:12:00.617Z,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T1055.011
1345,attack-pattern,attack-pattern--005a06c6-14bf-4118-afa0-ebcd8a...,3.3.0,Scheduled Task,1.8,Adversaries may abuse the Windows Task Schedul...,identity--c78cb6e5-0c4b-4611-8297-d1b8b55e40b5,2019-11-27T14:58:00.429Z,2026-05-12T15:12:00.618Z,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T1053.005
1346,attack-pattern,attack-pattern--005cc321-08ce-4d17-b1ea-cb5275...,3.3.0,Socket Filters,2.0,Adversaries may attach filters to a network so...,identity--c78cb6e5-0c4b-4611-8297-d1b8b55e40b5,2022-09-30T21:18:41.930Z,2026-05-12T15:12:00.619Z,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T1205.002
1347,attack-pattern,attack-pattern--00d0b012-8a03-410e-95de-5826bf...,3.2.0,Indicator Removal from Tools,1.1,If a malicious tool is detected and quarantine...,identity--c78cb6e5-0c4b-4611-8297-d1b8b55e40b5,2017-05-31T21:30:54.176Z,2026-04-14T22:53:15.802Z,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T1066
1348,attack-pattern,attack-pattern--00f90846-cbd1-4fc5-9233-df5c2b...,3.3.0,Archive via Utility,1.3,Adversaries may use utilities to compress and/...,identity--c78cb6e5-0c4b-4611-8297-d1b8b55e40b5,2020-02-20T21:01:25.428Z,2026-05-12T15:12:00.619Z,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T1560.001

In [7]:
print("Total attack-patterns:", len(techniques_df))

print(
    techniques_df["technique_id"].head(20)
)

print(
    "Missing technique IDs:",
    techniques_df["technique_id"].isna().sum()
)

print(
    "Unique technique IDs:",
    techniques_df["technique_id"].nunique()
)

print(
    "Supported IDs:",
    len(needed_technique_ids)
)

print(
    "Matching IDs:",
    techniques_df["technique_id"]
    .isin(needed_technique_ids)
    .sum()
)

Total attack-patterns: 858
1344    T1055.011
1345    T1053.005
1346    T1205.002
1347        T1066
1348    T1560.001
1349    T1021.005
1350        T1047
1351        T1687
1352        T1156
1353        T1113
1354    T1027.011
1355        T1067
1356        T1037
1357        T1557
1358        T1033
1359        T1583
1360    T1218.011
1361        T1613
1362    T1583.007
1363        T1143
Name: technique_id, dtype: object
Missing technique IDs: 0
Unique technique IDs: 858
Supported IDs: 53
Matching IDs: 53

In [8]:
# Start from the raw STIX attack-pattern objects
techniques_df = df[df["type"] == "attack-pattern"].copy()

print("Before filtering:", techniques_df.shape)

# Extract MITRE ATT&CK technique ID
techniques_df["technique_id"] = (
    techniques_df["external_references"]
    .apply(get_attack_id)
)

# Keep only techniques supported by Wazuh/Zeek
techniques_df = techniques_df[
    techniques_df["technique_id"].isin(needed_technique_ids)
].copy()

print("After filtering:", techniques_df.shape)

Before filtering: (858, 43)
After filtering: (53, 44)

In [9]:
techniques_df.head()

,type,id,x_mitre_attack_spec_version,name,x_mitre_version,description,created_by_ref,created,modified,x_mitre_contents,...,x_mitre_log_sources,x_mitre_collection_layers,x_mitre_analytic_refs,relationship_type,source_ref,target_ref,identity_class,definition,definition_type,technique_id
1345,attack-pattern,attack-pattern--005a06c6-14bf-4118-afa0-ebcd8a...,3.3.0,Scheduled Task,1.8,Adversaries may abuse the Windows Task Schedul...,identity--c78cb6e5-0c4b-4611-8297-d1b8b55e40b5,2019-11-27T14:58:00.429Z,2026-05-12T15:12:00.618Z,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T1053.005
1358,attack-pattern,attack-pattern--03d7999c-1f4c-42cc-8373-e7690d...,3.3.0,System Owner/User Discovery,1.6,Adversaries may attempt to identify the primar...,identity--c78cb6e5-0c4b-4611-8297-d1b8b55e40b5,2017-05-31T21:30:35.733Z,2026-05-12T15:12:00.620Z,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T1033
1371,attack-pattern,attack-pattern--09312b1a-c3c6-4b45-9844-3ccc78...,3.2.0,Gather Victim Host Information,1.2,Adversaries may gather information about the v...,identity--c78cb6e5-0c4b-4611-8297-d1b8b55e40b5,2020-10-02T16:39:33.966Z,2025-10-24T17:48:21.583Z,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T1592
1376,attack-pattern,attack-pattern--09c4c11e-4fa1-4f8c-8dad-3cf8e6...,3.3.0,Password Guessing,1.7,Adversaries with no prior knowledge of legitim...,identity--c78cb6e5-0c4b-4611-8297-d1b8b55e40b5,2020-02-11T18:38:22.617Z,2026-05-12T15:12:00.620Z,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T1110.001
1401,attack-pattern,attack-pattern--0ff59227-8aa8-4c09-bf1f-925605...,3.2.0,DNS,1.2,Adversaries may gather information about the v...,identity--c78cb6e5-0c4b-4611-8297-d1b8b55e40b5,2020-10-02T15:47:10.102Z,2025-10-24T17:48:24.404Z,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,T1590.002

In [11]:
needed_attack_pattern_ids = set(techniques_df["id"])

group_technique_relationships = relationships_df[
    (relationships_df["relationship_type"] == "uses") &
    (relationships_df["source_ref"].str.startswith(
        "intrusion-set--", na=False
    )) &
    (relationships_df["target_ref"].isin(
        needed_attack_pattern_ids
    ))
].copy()

In [13]:
group_technique_relationships.shape

(1298, 43)

In [14]:
techniques_df.shape

(53, 44)

In [15]:
group_technique_relationships.head()

,type,id,x_mitre_attack_spec_version,name,x_mitre_version,description,created_by_ref,created,modified,x_mitre_contents,...,x_mitre_mutable_elements,x_mitre_log_sources,x_mitre_collection_layers,x_mitre_analytic_refs,relationship_type,source_ref,target_ref,identity_class,definition,definition_type
7580,relationship,relationship--064cfeb5-9ddb-4dd2-ada4-cf9e6560...,3.3.0,NaN,NaN,[APT38](https://attack.mitre.org/groups/G0082)...,identity--c78cb6e5-0c4b-4611-8297-d1b8b55e40b5,2021-09-29T22:24:15.758Z,2026-07-31T20:48:23.023Z,NaN,...,NaN,NaN,NaN,NaN,uses,intrusion-set--00f67a77-86a4-4adf-be26-1a54fc7...,attack-pattern--03d7999c-1f4c-42cc-8373-e7690d...,NaN,NaN,NaN
7583,relationship,relationship--11ab80ae-29e7-45a4-8d92-53493e29...,3.3.0,NaN,NaN,[APT38](https://attack.mitre.org/groups/G0082)...,identity--c78cb6e5-0c4b-4611-8297-d1b8b55e40b5,2019-09-09T17:51:47.352Z,2026-07-31T20:48:23.045Z,NaN,...,NaN,NaN,NaN,NaN,uses,intrusion-set--00f67a77-86a4-4adf-be26-1a54fc7...,attack-pattern--7e150503-88e7-4861-866b-ff1ac8...,NaN,NaN,NaN
7588,relationship,relationship--2012985d-6529-4944-a2d2-892d5675...,3.3.0,NaN,NaN,[APT38](https://attack.mitre.org/groups/G0082)...,identity--c78cb6e5-0c4b-4611-8297-d1b8b55e40b5,2021-09-29T22:24:15.753Z,2026-07-31T20:48:23.095Z,NaN,...,NaN,NaN,NaN,NaN,uses,intrusion-set--00f67a77-86a4-4adf-be26-1a54fc7...,attack-pattern--2959d63f-73fd-46a1-abd2-109d7d...,NaN,NaN,NaN
7590,relationship,relationship--2d27c0d9-7e8e-4713-b3e1-0d82db27...,3.3.0,NaN,NaN,[APT38](https://attack.mitre.org/groups/G0082)...,identity--c78cb6e5-0c4b-4611-8297-d1b8b55e40b5,2019-01-29T21:27:25.332Z,2026-07-31T20:48:23.109Z,NaN,...,NaN,NaN,NaN,NaN,uses,intrusion-set--00f67a77-86a4-4adf-be26-1a54fc7...,attack-pattern--d742a578-d70e-4d0e-96a6-02a9c3...,NaN,NaN,NaN
7591,relationship,relationship--2f19f736-a547-47c3-ae26-40a0d13c...,3.3.0,NaN,NaN,[APT38](https://attack.mitre.org/groups/G0082)...,identity--c78cb6e5-0c4b-4611-8297-d1b8b55e40b5,2021-09-29T22:24:15.696Z,2026-07-31T20:48:23.117Z,NaN,...,NaN,NaN,NaN,NaN,uses,intrusion-set--00f67a77-86a4-4adf-be26-1a54fc7...,attack-pattern--7bc57495-ea59-4380-be31-a64af1...,NaN,NaN,NaN

In [24]:
group_technique_relationships["target_ref"].nunique()

49

In [38]:
import json
from datetime import datetime


# ============================================================
# 1. Helper functions
# ============================================================

def get_attack_id(external_references):
    """
    Extract MITRE ATT&CK external_id from STIX external_references.
    Example:
        T1059
        T1059.001
        T1105
    """
    if not isinstance(external_references, list):
        return None

    for ref in external_references:
        if ref.get("source_name") == "mitre-attack":
            return ref.get("external_id")

    return None


def get_mitre_group_id(external_references):
    """
    Extract the MITRE ATT&CK group ID, e.g. G0001.
    """
    if not isinstance(external_references, list):
        return None

    for ref in external_references:
        if ref.get("source_name") == "mitre-attack":
            external_id = ref.get("external_id")

            if external_id and external_id.startswith("G"):
                return external_id

    return None


# ============================================================
# 2. Make sure techniques have their ATT&CK IDs
# ============================================================

if "technique_id" not in techniques_df.columns:
    techniques_df["technique_id"] = (
        techniques_df["external_references"]
        .apply(get_attack_id)
    )


# ============================================================
# 3. Add MITRE group IDs
# ============================================================

groups_df = groups_df.copy()

groups_df["group_id"] = (
    groups_df["external_references"]
    .apply(get_mitre_group_id)
)


# ============================================================
# 4. Build technique lookup
# ============================================================

technique_lookup = {}

for _, row in techniques_df.iterrows():

    technique_id = row["technique_id"]

    if not technique_id:
        continue

    # Prefer your existing Wazuh/Zeek mapping for tactic
    tactic = None

    if technique_id in supported_techniques:
        tactic = supported_techniques[technique_id].get("tactic")

    # Make sure tactics are always a list
    if tactic:
        if isinstance(tactic, list):
            tactics = tactic
        else:
            tactics = [tactic]
    else:
        tactics = []

    technique_lookup[technique_id] = {
        "technique_name": row["name"],
        "stix_id": row["id"],
        "tactics": tactics
    }


# ============================================================
# 5. Build group lookup
# ============================================================

group_lookup = {}

for _, row in groups_df.iterrows():

    group_id = row["group_id"]

    if not group_id:
        continue

    group_lookup[group_id] = {
        "group_name": row["name"],
        "stix_id": row["id"]
    }

# ============================================================
# 6. Build lookup dictionaries
# ============================================================

group_by_stix_id = {
    row["id"]: row
    for _, row in groups_df.iterrows()
}

technique_by_stix_id = {
    row["id"]: row
    for _, row in techniques_df.iterrows()
}


# ============================================================
# Build normalized Group → Technique relationships
# ============================================================

group_technique_relationships = []

for _, row in relationships_df.iterrows():

    source_ref = row["source_ref"]
    target_ref = row["target_ref"]

    group = group_by_stix_id.get(source_ref)
    technique = technique_by_stix_id.get(target_ref)

    if group is None or technique is None:
        continue

    group_id = group["group_id"]
    technique_id = technique["technique_id"]

    if not group_id or not technique_id:
        continue

    relationship = {
        "relationship_id": row["id"],
        "relationship_type": row["relationship_type"],

        "group_id": group_id,
        "group_stix_id": source_ref,

        "technique_id": technique_id,
        "technique_stix_id": target_ref,

        "source": {
            "type": "MITRE_ATT&CK_STIX",
            "confidence": 1.0
        }
    }

    if (
        "description" in row.index
        and isinstance(row["description"], str)
        and row["description"].strip()
    ):
        relationship["description"] = row["description"]

    group_technique_relationships.append(relationship)


# ============================================================
# 7. Build technique-centric relationships
#
# Source of truth:
#     group_technique_relationships
#
# For each technique:
#
#     technique
#          ↓
#     groups using it
#          ↓
#     other techniques used by those groups
#          ↓
#     shared group count
#
# Additional statistical features:
#
#     cooccurrence =
#         shared_groups / input_technique_groups
#
#     global_rarity =
#         log(total_groups / candidate_group_count)
#
#     combined_score =
#         cooccurrence * global_rarity
# ============================================================

import math

technique_relations = {}


# ------------------------------------------------------------
# Build:
#
# technique → groups
#
# directly from normalized relationships
# ------------------------------------------------------------

technique_to_groups = {}

for relationship in group_technique_relationships:

    if relationship["relationship_type"] != "uses":
        continue

    technique_id = relationship["technique_id"]
    group_id = relationship["group_id"]

    if technique_id not in technique_to_groups:
        technique_to_groups[technique_id] = set()

    technique_to_groups[technique_id].add(group_id)


# ------------------------------------------------------------
# Build:
#
# group → techniques
#
# directly from normalized relationships
# ------------------------------------------------------------

group_to_techniques = {}

for relationship in group_technique_relationships:

    if relationship["relationship_type"] != "uses":
        continue

    group_id = relationship["group_id"]
    technique_id = relationship["technique_id"]

    if group_id not in group_to_techniques:
        group_to_techniques[group_id] = set()

    group_to_techniques[group_id].add(technique_id)


# ------------------------------------------------------------
# Total groups participating in valid "uses" relationships
#
# This is the population used for global rarity.
# ------------------------------------------------------------

all_used_groups = set()

for groups in technique_to_groups.values():
    all_used_groups.update(groups)

total_groups = len(all_used_groups)


# ------------------------------------------------------------
# Generate technique-centric knowledge
# ------------------------------------------------------------

for input_technique in technique_lookup.keys():

    # --------------------------------------------------------
    # Groups using the input technique
    # --------------------------------------------------------

    groups_using_input = sorted(
        technique_to_groups.get(
            input_technique,
            set()
        )
    )

    input_technique_group_count = len(
        groups_using_input
    )


    # --------------------------------------------------------
    # Find techniques used by those groups
    # --------------------------------------------------------

    related = {}

    for group_id in groups_using_input:

        techniques_used_by_group = group_to_techniques.get(
            group_id,
            set()
        )

        for other_technique in techniques_used_by_group:

            # Don't relate technique to itself
            if other_technique == input_technique:
                continue

            if other_technique not in related:

                related[other_technique] = {
                    "group_count": 0,
                    "groups": []
                }

            if group_id not in related[other_technique]["groups"]:

                related[other_technique]["groups"].append(
                    group_id
                )


    # --------------------------------------------------------
    # Calculate statistical features
    # --------------------------------------------------------

    for other_technique, relation in related.items():

        # -----------------------------------------------
        # Sort groups
        # -----------------------------------------------

        relation["groups"].sort()


        # -----------------------------------------------
        # Number of shared groups
        # -----------------------------------------------

        shared_groups = len(
            relation["groups"]
        )

        relation["group_count"] = shared_groups


        # -----------------------------------------------
        # Co-occurrence
        #
        # shared groups / groups using input technique
        #
        # Example:
        #
        # input T1048 → 2 groups
        # candidate T1016 → shared by both
        #
        # cooccurrence = 2 / 2 = 1.0
        # -----------------------------------------------

        if input_technique_group_count > 0:

            cooccurrence = (
                shared_groups
                / input_technique_group_count
            )

        else:

            cooccurrence = 0.0


        relation["cooccurrence"] = round(
            cooccurrence,
            6
        )


        # -----------------------------------------------
        # Candidate's global group count
        #
        # This is NOT the shared group count.
        #
        # We need the total number of groups that use
        # this candidate technique across the whole DB.
        # -----------------------------------------------

        candidate_groups = technique_to_groups.get(
            other_technique,
            set()
        )

        candidate_group_count = len(
            candidate_groups
        )


        # -----------------------------------------------
        # Global rarity / IDF
        #
        # log(total_groups / candidate_group_count)
        # -----------------------------------------------

        if (
            total_groups > 0
            and candidate_group_count > 0
        ):

            global_rarity = math.log(
                total_groups
                / candidate_group_count
            )

        else:

            global_rarity = 0.0


        relation["global_rarity"] = round(
            global_rarity,
            6
        )


        # -----------------------------------------------
        # Combined score
        #
        # cooccurrence × global rarity
        # -----------------------------------------------

        combined_score = (
            cooccurrence
            * global_rarity
        )

        relation["combined_score"] = round(
            combined_score,
            6
        )


    # --------------------------------------------------------
    # Sort by combined score
    #
    # Tie breakers:
    #   1. cooccurrence
    #   2. group_count
    #   3. technique ID
    # --------------------------------------------------------

    related = dict(
        sorted(
            related.items(),
            key=lambda item: (
                -item[1]["combined_score"],
                -item[1]["cooccurrence"],
                -item[1]["group_count"],
                item[0]
            )
        )
    )


    # --------------------------------------------------------
    # Store
    # --------------------------------------------------------

    technique_relations[input_technique] = {

        "group_count": input_technique_group_count,

        "groups": groups_using_input,

        "related_techniques": related
    }




# ============================================================
# 8. Build the final database
# ============================================================

database = {

    "metadata": {
        "dataset_name": "attack_progression_knowledge",
        "version": "0.1.0",
        "created_at": datetime.utcnow().isoformat() + "Z",

        "primary_source": {
            "name": "MITRE ATT&CK",
            "format": "STIX 2.1",
            "domain": "enterprise-attack"
        },

        "technique_vocabulary": {
            "source": "Wazuh/Zeek semantic mapping",
            "supported_technique_count": len(technique_lookup)
        },

        "relationship_semantics": {
            "uses": "Group is associated with / uses a technique",
            "important_note": (
                "MITRE ATT&CK uses relationships do not imply "
                "chronological technique ordering."
            )
        },

        "candidate_scoring": {
            "cooccurrence": {
                "formula": "shared_groups / input_technique_groups",
                "description": (
                    "Fraction of groups using the input technique "
                    "that also use the candidate technique."
                )
            },
        
            "global_rarity": {
                "formula": "log(total_groups / candidate_group_count)",
                "description": (
                    "IDF-like measure indicating how globally "
                    "discriminative the candidate technique is."
                )
            },
        
            "combined_score": {
                "formula": "cooccurrence * global_rarity",
                "description": (
                    "Initial candidate-ranking score based on "
                    "group co-occurrence and global rarity."
                )
            },
        
            "important_note": (
                "These scores measure association and candidate "
                "relevance. They do not represent chronological "
                "attack progression or next-technique probability."
            )
        }  
    },


    # ========================================================
    # TECHNIQUES
    # ========================================================

    "techniques": technique_lookup,


    # ========================================================
    # GROUPS
    # ========================================================

    "groups": group_lookup,


    # ========================================================
    # RAW / NORMALIZED GROUP → TECHNIQUE EDGES
    # ========================================================

    "group_technique_relationships": group_technique_relationships,


    # ========================================================
    # TECHNIQUE → RELATED TECHNIQUES
    # ========================================================

    "technique_relations": technique_relations,


    # ========================================================
    # SEQUENCE EVIDENCE
    #
    # Empty for now because STIX does not provide the
    # chronological ordering we need.
    # ========================================================

    "sequence_evidence": []
}


# ============================================================
# 9. Save JSON
# ============================================================

output_file = "attack_progression_knowledge.json"

with open(output_file, "w", encoding="utf-8") as f:
    json.dump(
        database,
        f,
        indent=2,
        ensure_ascii=False
    )


print(f"Database saved to: {output_file}")

print()
print("Statistics")
print("--------------------------------")
print("Techniques:", len(database["techniques"]))
print("Groups:", len(database["groups"]))
print(
    "Group-Technique relationships:",
    len(database["group_technique_relationships"])
)
print(
    "Technique relation entries:",
    len(database["technique_relations"])
)

Database saved to: attack_progression_knowledge.json

Statistics
--------------------------------
Techniques: 53
Groups: 191
Group-Technique relationships: 1298
Technique relation entries: 53

C:\Users\tahay\AppData\Local\Temp\ipykernel_13736\731601039.py:499: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  "created_at": datetime.utcnow().isoformat() + "Z",

In [1]:
import json

# ============================================================
# Load database
# ============================================================

with open(
    "attack_progression_knowledge.json",
    "r",
    encoding="utf-8"
) as f:
    db = json.load(f)


# ============================================================
# Input technique
# ============================================================

input_technique = "T1046"


# ============================================================
# Get technique information
# ============================================================

technique = db["techniques"].get(input_technique)

if technique is None:
    print(f"Technique {input_technique} not found.")
    exit()


print("=" * 70)
print("INPUT TECHNIQUE")
print("=" * 70)

print(f"ID      : {input_technique}")
print(f"Name    : {technique['technique_name']}")
print(f"Tactics : {', '.join(technique['tactics'])}")

# ============================================================
# Get technique relation record
# ============================================================

technique_relation = db["technique_relations"].get(
    input_technique
)

if technique_relation is None:
    print(
        f"No relation data found for {input_technique}"
    )
    exit()


# ============================================================
# Groups using input technique
# ============================================================

groups_using_technique = technique_relation["groups"]

print()
print("=" * 70)
print("GROUPS USING THE INPUT TECHNIQUE")
print("=" * 70)

for group_id in groups_using_technique:

    group = db["groups"].get(group_id)

    if group:
        print(
            f"{group_id} | "
            f"{group['group_name']}"
        )

print()
print(
    f"Total groups: "
    f"{len(groups_using_technique)}"
)

# ============================================================
# Related techniques
# ============================================================

related_techniques = technique_relation[
    "related_techniques"
]

print()
print("=" * 100)
print("RELATED TECHNIQUES")
print("=" * 100)

for rank, (technique_id, relation) in enumerate(
    related_techniques.items(),
    start=1
):

    technique_info = db["techniques"].get(
        technique_id
    )

    if not technique_info:
        continue

    print(
        f"{rank:>2}. "
        f"{technique_id:<12} | "
        f"{technique_info['technique_name']:<55} | "
        f"Groups: {relation['group_count']:<3} | "
        f"Co-occ: {relation['cooccurrence']:.4f} | "
        f"Rarity: {relation['global_rarity']:.4f} | "
        f"Score: {relation['combined_score']:.4f}"
    )

print()
print(
    f"Total related techniques: "
    f"{len(related_techniques)}"
)

======================================================================
INPUT TECHNIQUE
======================================================================
ID      : T1046
Name    : Network Service Discovery
Tactics : Reconnaissance

======================================================================
GROUPS USING THE INPUT TECHNIQUE
======================================================================
G0019 | Naikon
G0027 | Threat Group-3390
G0030 | Lotus Blossom
G0032 | Lazarus Group
G0037 | FIN6
G0039 | Suckfly
G0045 | menuPass
G0049 | OilRig
G0050 | APT32
G0059 | Magic Hound
G0077 | Leafminer
G0080 | Cobalt Group
G0081 | Tropic Trooper
G0087 | APT39
G0096 | APT41
G0098 | BlackTech
G0105 | DarkVishnya
G0106 | Rocke
G0114 | Chimera
G0117 | Fox Kitten
G0129 | Mustang Panda
G0135 | BackdoorDiplomacy
G0139 | TeamTNT
G1003 | Ember Bear
G1016 | FIN13
G1017 | Volt Typhoon
G1030 | Agrius
G1032 | INC Ransom
G1039 | RedCurl
G1043 | BlackByte
G1051 | Medusa Group

Total groups: 31

====================================================================================================
RELATED TECHNIQUES
====================================================================================================
 1. T1018        | Remote System Discovery                                 | Groups: 19  | Co-occ: 0.6129 | Rarity: 1.3678 | Score: 0.8383
 2. T1049        | System Network Connections Discovery                    | Groups: 16  | Co-occ: 0.5161 | Rarity: 1.6157 | Score: 0.8339
 3. T1505.003    | Web Shell                                               | Groups: 15  | Co-occ: 0.4839 | Rarity: 1.6474 | Score: 0.7971
 4. T1543.003    | Windows Service                                         | Groups: 13  | Co-occ: 0.4194 | Rarity: 1.8233 | Score: 0.7646
 5. T1021.001    | Remote Desktop Protocol                                 | Groups: 16  | Co-occ: 0.5161 | Rarity: 1.4705 | Score: 0.7590
 6. T1087.002    | Domain Account                                          | Groups: 13  | Co-occ: 0.4194 | Rarity: 1.7141 | Score: 0.7188
 7. T1016        | System Network Configuration Discovery                  | Groups: 17  | Co-occ: 0.5484 | Rarity: 1.2972 | Score: 0.7114
 8. T1572        | Protocol Tunneling                                      | Groups: 9   | Co-occ: 0.2903 | Rarity: 2.3734 | Score: 0.6890
 9. T1003.001    | LSASS Memory                                            | Groups: 16  | Co-occ: 0.5161 | Rarity: 1.2972 | Score: 0.6695
10. T1190        | Exploit Public-Facing Application                       | Groups: 16  | Co-occ: 0.5161 | Rarity: 1.2528 | Score: 0.6466
11. T1021.004    | SSH                                                     | Groups: 9   | Co-occ: 0.2903 | Rarity: 2.1370 | Score: 0.6204
12. T1083        | File and Directory Discovery                            | Groups: 17  | Co-occ: 0.5484 | Rarity: 1.1302 | Score: 0.6198
13. T1071.004    | DNS                                                     | Groups: 7   | Co-occ: 0.2258 | Rarity: 2.6835 | Score: 0.6060
14. T1053.005    | Scheduled Task                                          | Groups: 17  | Co-occ: 0.5484 | Rarity: 1.0924 | Score: 0.5991
15. T1071.001    | Web Protocols                                           | Groups: 17  | Co-occ: 0.5484 | Rarity: 1.0384 | Score: 0.5694
16. T1078        | Valid Accounts                                          | Groups: 14  | Co-occ: 0.4516 | Rarity: 1.2313 | Score: 0.5561
17. T1547.001    | Registry Run Keys / Startup Folder                      | Groups: 16  | Co-occ: 0.5161 | Rarity: 1.0384 | Score: 0.5359
18. T1110        | Brute Force                                             | Groups: 7   | Co-occ: 0.2258 | Rarity: 2.3088 | Score: 0.5213
19. T1033        | System Owner/User Discovery                             | Groups: 11  | Co-occ: 0.3548 | Rarity: 1.3925 | Score: 0.4941
20. T1021.002    | SMB/Windows Admin Shares                                | Groups: 8   | Co-occ: 0.2581 | Rarity: 1.7856 | Score: 0.4608
21. T1133        | External Remote Services                                | Groups: 8   | Co-occ: 0.2581 | Rarity: 1.7492 | Score: 0.4514
22. T1059        | Command and Scripting Interpreter                       | Groups: 6   | Co-occ: 0.1935 | Rarity: 2.2482 | Score: 0.4351
23. T1203        | Exploitation for Client Execution                       | Groups: 10  | Co-occ: 0.3226 | Rarity: 1.3437 | Score: 0.4335
24. T1048.003    | Exfiltration Over Unencrypted Non-C2 Protocol           | Groups: 5   | Co-occ: 0.1613 | Rarity: 2.6835 | Score: 0.4328
25. T1110.003    | Password Spraying                                       | Groups: 5   | Co-occ: 0.1613 | Rarity: 2.6835 | Score: 0.4328
26. T1059.001    | PowerShell                                              | Groups: 21  | Co-occ: 0.6774 | Rarity: 0.6388 | Score: 0.4327
27. T1105        | Ingress Tool Transfer                                   | Groups: 21  | Co-occ: 0.6774 | Rarity: 0.6041 | Score: 0.4092
28. T1069.002    | Domain Groups                                           | Groups: 5   | Co-occ: 0.1613 | Rarity: 2.5165 | Score: 0.4059
29. T1041        | Exfiltration Over C2 Channel                            | Groups: 7   | Co-occ: 0.2258 | Rarity: 1.7856 | Score: 0.4032
30. T1039        | Data from Network Shared Drive                          | Groups: 4   | Co-occ: 0.1290 | Rarity: 3.0020 | Score: 0.3874
31. T1027        | Obfuscated Files or Information                         | Groups: 5   | Co-occ: 0.1613 | Rarity: 2.1910 | Score: 0.3534
32. T1059.004    | Unix Shell                                              | Groups: 4   | Co-occ: 0.1290 | Rarity: 2.6835 | Score: 0.3463
33. T1095        | Non-Application Layer Protocol                          | Groups: 4   | Co-occ: 0.1290 | Rarity: 2.5965 | Score: 0.3350
34. T1210        | Exploitation of Remote Services                         | Groups: 4   | Co-occ: 0.1290 | Rarity: 2.5965 | Score: 0.3350
35. T1595.002    | Vulnerability Scanning                                  | Groups: 4   | Co-occ: 0.1290 | Rarity: 2.3734 | Score: 0.3062
36. T1204.002    | Malicious File                                          | Groups: 14  | Co-occ: 0.4516 | Rarity: 0.6271 | Score: 0.2832
37. T1595.001    | Scanning IP Blocks                                      | Groups: 2   | Co-occ: 0.0645 | Rarity: 4.3883 | Score: 0.2831
38. T1189        | Drive-by Compromise                                     | Groups: 5   | Co-occ: 0.1613 | Rarity: 1.6474 | Score: 0.2657
39. T1567        | Exfiltration Over Web Service                           | Groups: 2   | Co-occ: 0.0645 | Rarity: 3.4720 | Score: 0.2240
40. T1592        | Gather Victim Host Information                          | Groups: 1   | Co-occ: 0.0323 | Rarity: 5.0814 | Score: 0.1639
41. T1048        | Exfiltration Over Alternative Protocol                  | Groups: 1   | Co-occ: 0.0323 | Rarity: 4.3883 | Score: 0.1416
42. T1568.002    | Domain Generation Algorithms                            | Groups: 1   | Co-occ: 0.0323 | Rarity: 4.3883 | Score: 0.1416
43. T1071.002    | File Transfer Protocols                                 | Groups: 1   | Co-occ: 0.0323 | Rarity: 3.4720 | Score: 0.1120

Total related techniques: 43

In [2]:
supported_techniques = {'T1590.001': {'technique_id': 'T1590.001',
  'technique_name': 'Gather Victim Network Information: Domain Properties',
  'tactic': 'Reconnaissance'},
 'T1016': {'technique_id': 'T1016',
  'technique_name': 'System Network Configuration Discovery',
  'tactic': 'Discovery'},
 'T1190': {'technique_id': 'T1190',
  'technique_name': 'Exploit Public-Facing Application',
  'tactic': 'Initial Access'},
 'T1133': {'technique_id': 'T1133',
  'technique_name': 'External Remote Services',
  'tactic': 'Initial Access'},
 'T1078': {'technique_id': 'T1078',
  'technique_name': 'Valid Accounts',
  'tactic': 'Initial Access'},
 'T1505.003': {'technique_id': 'T1505.003',
  'technique_name': 'Server Software Component: Web Shell',
  'tactic': 'Persistence'},
 'T1105': {'technique_id': 'T1105',
  'technique_name': 'Ingress Tool Transfer',
  'tactic': 'Command and Control'},
 'T1203': {'technique_id': 'T1203',
  'technique_name': 'Exploitation for Client Execution',
  'tactic': 'Execution'},
 'T1204': {'technique_id': 'T1204',
  'technique_name': 'User Execution',
  'tactic': 'Execution'},
 'T1021.001': {'technique_id': 'T1021.001',
  'technique_name': 'Remote Services: Remote Desktop Protocol',
  'tactic': 'Lateral Movement'},
 'T1021.002': {'technique_id': 'T1021.002',
  'technique_name': 'Remote Services: SMB/Windows Admin Shares',
  'tactic': 'Lateral Movement'},
 'T1021.004': {'technique_id': 'T1021.004',
  'technique_name': 'Remote Services: SSH',
  'tactic': 'Lateral Movement'},
 'T1046': {'technique_id': 'T1046',
  'technique_name': 'Network Service Scanning',
  'tactic': 'Reconnaissance'},
 'T1595.001': {'technique_id': 'T1595.001',
  'technique_name': 'Active Scanning: Scanning IP Blocks',
  'tactic': 'Reconnaissance'},
 'T1595.002': {'technique_id': 'T1595.002',
  'technique_name': 'Active Scanning: Vulnerability Scanning',
  'tactic': 'Reconnaissance'},
 'T1590.002': {'technique_id': 'T1590.002',
  'technique_name': 'Gather Victim Network Information: DNS',
  'tactic': 'Reconnaissance'},
 'T1592': {'technique_id': 'T1592',
  'technique_name': 'Gather Victim Host Information',
  'tactic': 'Reconnaissance'},
 'T1083': {'technique_id': 'T1083',
  'technique_name': 'File and Directory Discovery',
  'tactic': 'Discovery'},
 'T1018': {'technique_id': 'T1018',
  'technique_name': 'Remote System Discovery',
  'tactic': 'Discovery'},
 'T1049': {'technique_id': 'T1049',
  'technique_name': 'System Network Connections Discovery',
  'tactic': 'Discovery'},
 'T1110': {'technique_id': 'T1110',
  'technique_name': 'Brute Force',
  'tactic': 'Credential Access'},
 'T1110.001': {'technique_id': 'T1110.001',
  'technique_name': 'Brute Force: Password Guessing',
  'tactic': 'Credential Access'},
 'T1110.003': {'technique_id': 'T1110.003',
  'technique_name': 'Brute Force: Password Spraying',
  'tactic': 'Credential Access'},
 'T1210': {'technique_id': 'T1210',
  'technique_name': 'Exploitation of Remote Services',
  'tactic': 'Lateral Movement'},
 'T1071.001': {'technique_id': 'T1071.001',
  'technique_name': 'Application Layer Protocol: Web Protocols',
  'tactic': 'Command and Control'},
 'T1071.004': {'technique_id': 'T1071.004',
  'technique_name': 'Application Layer Protocol: DNS',
  'tactic': 'Command and Control'},
 'T1572': {'technique_id': 'T1572',
  'technique_name': 'Protocol Tunneling',
  'tactic': 'Command and Control'},
 'T1095': {'technique_id': 'T1095',
  'technique_name': 'Non-Application Layer Protocol',
  'tactic': 'Command and Control'},
 'T1041': {'technique_id': 'T1041',
  'technique_name': 'Exfiltration Over C2 Channel',
  'tactic': 'Exfiltration'},
 'T1048.003': {'technique_id': 'T1048.003',
  'technique_name': 'Exfiltration Over Unencrypted/Obfuscated Non-C2 Protocol',
  'tactic': 'Exfiltration'},
 'T1567': {'technique_id': 'T1567',
  'technique_name': 'Exfiltration Over Web Service',
  'tactic': 'Exfiltration'},
 'T1048': {'technique_id': 'T1048',
  'technique_name': 'Exfiltration Over Alternative Protocol',
  'tactic': 'Exfiltration'},
 'T1039': {'technique_id': 'T1039',
  'technique_name': 'Data from Network Shared Drive',
  'tactic': 'Collection'},
 'T1213': {'technique_id': 'T1213',
  'technique_name': 'Data from Information Repositories',
  'tactic': 'Collection'},
 'T1071.002': {'technique_id': 'T1071.002',
  'technique_name': 'Application Layer Protocol: File Transfer Protocols',
  'tactic': 'Command and Control'},
 'T1496': {'technique_id': 'T1496',
  'technique_name': 'Resource Hijacking',
  'tactic': 'Impact'},
 'T1497': {'technique_id': 'T1497',
  'technique_name': 'Virtualization/Sandbox Evasion',
  'tactic': 'Defense Evasion'},
 'T1568.002': {'technique_id': 'T1568.002',
  'technique_name': 'Dynamic Resolution: Domain Generation Algorithms',
  'tactic': 'Command and Control'},
 'T1189': {'technique_id': 'T1189',
  'technique_name': 'Drive-by Compromise',
  'tactic': 'Initial Access'},
 'T1059.001': {'technique_id': 'T1059.001',
  'technique_name': 'Command and Scripting Interpreter: PowerShell',
  'tactic': 'Execution'},
 'T1059': {'technique_id': 'T1059',
  'technique_name': 'Command and Scripting Interpreter',
  'tactic': 'Execution'},
 'T1003.001': {'technique_id': 'T1003.001',
  'technique_name': 'OS Credential Dumping: LSASS Memory',
  'tactic': 'Credential Access'},
 'T1003.008': {'technique_id': 'T1003.008',
  'technique_name': 'OS Credential Dumping: /etc/passwd and /etc/shadow',
  'tactic': 'Credential Access'},
 'T1027': {'technique_id': 'T1027',
  'technique_name': 'Obfuscated Files or Information',
  'tactic': 'Defense Evasion'},
 'T1204.002': {'technique_id': 'T1204.002',
  'technique_name': 'User Execution: Malicious File',
  'tactic': 'Execution'},
 'T1547.001': {'technique_id': 'T1547.001',
  'technique_name': 'Boot or Logon Autostart Execution: Registry Run Keys',
  'tactic': 'Persistence'},
 'T1053.005': {'technique_id': 'T1053.005',
  'technique_name': 'Scheduled Task/Job: Cron',
  'tactic': 'Persistence'},
 'T1543.003': {'technique_id': 'T1543.003',
  'technique_name': 'Create or Modify System Process: Windows Service',
  'tactic': 'Persistence'},
 'T1087.002': {'technique_id': 'T1087.002',
  'technique_name': 'Account Discovery: Domain Account',
  'tactic': 'Discovery'},
 'T1069.002': {'technique_id': 'T1069.002',
  'technique_name': 'Permission Groups Discovery: Domain Groups',
  'tactic': 'Discovery'},
 'T1059.004': {'technique_id': 'T1059.004',
  'technique_name': 'Unix Shell',
  'tactic': 'Execution'},
 'T1548.003': {'technique_id': 'T1548.003',
  'technique_name': 'Sudo and Sudo Caching',
  'tactic': 'Privilege Escalation'},
 'T1033': {'technique_id': 'T1033',
  'technique_name': 'System Owner/User Discovery',
  'tactic': 'Discovery'}}
needed_technique_ids = set(supported_techniques.keys())

In [6]:
import json

# ============================================================
# Load database
# ============================================================

with open(
    "attack_progression_knowledge.json",
    "r",
    encoding="utf-8"
) as f:
    db = json.load(f)


# ============================================================
# Input technique
# ============================================================

input_technique = "T1046"


# ============================================================
# Get technique information
# ============================================================

technique = db["techniques"].get(input_technique)

if technique is None:
    print(f"Technique {input_technique} not found.")
    exit()


print("=" * 70)
print("INPUT TECHNIQUE")
print("=" * 70)

print(f"ID      : {input_technique}")
print(f"Name    : {technique['technique_name']}")
print(f"Tactics : {', '.join(technique['tactics'])}")

# ============================================================
# Get technique relation record
# ============================================================

technique_relation = db["technique_relations"].get(
    input_technique
)

if technique_relation is None:
    print(
        f"No relation data found for {input_technique}"
    )
    exit()


# ============================================================
# Groups using input technique
# ============================================================

groups_using_technique = technique_relation["groups"]

print()
print("=" * 70)
print("GROUPS USING THE INPUT TECHNIQUE")
print("=" * 70)

for group_id in groups_using_technique:

    group = db["groups"].get(group_id)

    if group:
        print(
            f"{group_id} | "
            f"{group['group_name']}"
        )

print()
print(
    f"Total groups: "
    f"{len(groups_using_technique)}"
)

# ============================================================
# Related techniques
# ============================================================

related_techniques = technique_relation[
    "related_techniques"
]

related_needed = []

SCORE_THRESHOLD = 0.40

related_needed = {
    technique_id: relation
    for technique_id, relation in related_techniques.items()
    if (
        technique_id in needed_technique_ids
        and relation["combined_score"] >= SCORE_THRESHOLD
    )
}

related_needed = dict(
    sorted(
        related_needed.items(),
        key=lambda x: x[1]["combined_score"],
        reverse=True
    )
)
print()
print("=" * 100)
print(f"SUPPORTED RELATED TECHNIQUES (SCORE >= {SCORE_THRESHOLD})")
print("=" * 100)

for rank, (technique_id, relation) in enumerate(
    related_needed.items(),
    start=1
):
    technique_info = db["techniques"].get(technique_id)

    if not technique_info:
        continue

    print(
        f"{rank:>2}. "
        f"{technique_id:<12} | "
        f"{technique_info['technique_name']:<55} | "
        f"Groups: {relation['group_count']:<3} | "
        f"Co-occ: {relation['cooccurrence']:.4f} | "
        f"Rarity: {relation['global_rarity']:.4f} | "
        f"Score: {relation['combined_score']:.4f}"
    )

print()
print(f"Threshold: {SCORE_THRESHOLD}")
print(f"Total candidates: {len(related_needed)}")

======================================================================
INPUT TECHNIQUE
======================================================================
ID      : T1046
Name    : Network Service Discovery
Tactics : Reconnaissance

======================================================================
GROUPS USING THE INPUT TECHNIQUE
======================================================================
G0019 | Naikon
G0027 | Threat Group-3390
G0030 | Lotus Blossom
G0032 | Lazarus Group
G0037 | FIN6
G0039 | Suckfly
G0045 | menuPass
G0049 | OilRig
G0050 | APT32
G0059 | Magic Hound
G0077 | Leafminer
G0080 | Cobalt Group
G0081 | Tropic Trooper
G0087 | APT39
G0096 | APT41
G0098 | BlackTech
G0105 | DarkVishnya
G0106 | Rocke
G0114 | Chimera
G0117 | Fox Kitten
G0129 | Mustang Panda
G0135 | BackdoorDiplomacy
G0139 | TeamTNT
G1003 | Ember Bear
G1016 | FIN13
G1017 | Volt Typhoon
G1030 | Agrius
G1032 | INC Ransom
G1039 | RedCurl
G1043 | BlackByte
G1051 | Medusa Group

Total groups: 31

====================================================================================================
SUPPORTED RELATED TECHNIQUES (SCORE >= 0.4)
====================================================================================================
 1. T1018        | Remote System Discovery                                 | Groups: 19  | Co-occ: 0.6129 | Rarity: 1.3678 | Score: 0.8383
 2. T1049        | System Network Connections Discovery                    | Groups: 16  | Co-occ: 0.5161 | Rarity: 1.6157 | Score: 0.8339
 3. T1505.003    | Web Shell                                               | Groups: 15  | Co-occ: 0.4839 | Rarity: 1.6474 | Score: 0.7971
 4. T1543.003    | Windows Service                                         | Groups: 13  | Co-occ: 0.4194 | Rarity: 1.8233 | Score: 0.7646
 5. T1021.001    | Remote Desktop Protocol                                 | Groups: 16  | Co-occ: 0.5161 | Rarity: 1.4705 | Score: 0.7590
 6. T1087.002    | Domain Account                                          | Groups: 13  | Co-occ: 0.4194 | Rarity: 1.7141 | Score: 0.7188
 7. T1016        | System Network Configuration Discovery                  | Groups: 17  | Co-occ: 0.5484 | Rarity: 1.2972 | Score: 0.7114
 8. T1572        | Protocol Tunneling                                      | Groups: 9   | Co-occ: 0.2903 | Rarity: 2.3734 | Score: 0.6890
 9. T1003.001    | LSASS Memory                                            | Groups: 16  | Co-occ: 0.5161 | Rarity: 1.2972 | Score: 0.6695
10. T1190        | Exploit Public-Facing Application                       | Groups: 16  | Co-occ: 0.5161 | Rarity: 1.2528 | Score: 0.6466
11. T1021.004    | SSH                                                     | Groups: 9   | Co-occ: 0.2903 | Rarity: 2.1370 | Score: 0.6204
12. T1083        | File and Directory Discovery                            | Groups: 17  | Co-occ: 0.5484 | Rarity: 1.1302 | Score: 0.6198
13. T1071.004    | DNS                                                     | Groups: 7   | Co-occ: 0.2258 | Rarity: 2.6835 | Score: 0.6060
14. T1053.005    | Scheduled Task                                          | Groups: 17  | Co-occ: 0.5484 | Rarity: 1.0924 | Score: 0.5991
15. T1071.001    | Web Protocols                                           | Groups: 17  | Co-occ: 0.5484 | Rarity: 1.0384 | Score: 0.5694
16. T1078        | Valid Accounts                                          | Groups: 14  | Co-occ: 0.4516 | Rarity: 1.2313 | Score: 0.5561
17. T1547.001    | Registry Run Keys / Startup Folder                      | Groups: 16  | Co-occ: 0.5161 | Rarity: 1.0384 | Score: 0.5359
18. T1110        | Brute Force                                             | Groups: 7   | Co-occ: 0.2258 | Rarity: 2.3088 | Score: 0.5213
19. T1033        | System Owner/User Discovery                             | Groups: 11  | Co-occ: 0.3548 | Rarity: 1.3925 | Score: 0.4941
20. T1021.002    | SMB/Windows Admin Shares                                | Groups: 8   | Co-occ: 0.2581 | Rarity: 1.7856 | Score: 0.4608
21. T1133        | External Remote Services                                | Groups: 8   | Co-occ: 0.2581 | Rarity: 1.7492 | Score: 0.4514
22. T1059        | Command and Scripting Interpreter                       | Groups: 6   | Co-occ: 0.1935 | Rarity: 2.2482 | Score: 0.4351
23. T1203        | Exploitation for Client Execution                       | Groups: 10  | Co-occ: 0.3226 | Rarity: 1.3437 | Score: 0.4335
24. T1048.003    | Exfiltration Over Unencrypted Non-C2 Protocol           | Groups: 5   | Co-occ: 0.1613 | Rarity: 2.6835 | Score: 0.4328
25. T1110.003    | Password Spraying                                       | Groups: 5   | Co-occ: 0.1613 | Rarity: 2.6835 | Score: 0.4328
26. T1059.001    | PowerShell                                              | Groups: 21  | Co-occ: 0.6774 | Rarity: 0.6388 | Score: 0.4327
27. T1105        | Ingress Tool Transfer                                   | Groups: 21  | Co-occ: 0.6774 | Rarity: 0.6041 | Score: 0.4092
28. T1069.002    | Domain Groups                                           | Groups: 5   | Co-occ: 0.1613 | Rarity: 2.5165 | Score: 0.4059
29. T1041        | Exfiltration Over C2 Channel                            | Groups: 7   | Co-occ: 0.2258 | Rarity: 1.7856 | Score: 0.4032

Threshold: 0.4
Total candidates: 29